
CREATE TABLE IF NOT EXISTS branches ( id SERIAL PRIMARY KEY, name TEXT UNIQUE NOT NULL );
CREATE TABLE IF NOT EXISTS users ( id SERIAL PRIMARY KEY, name TEXT NOT NULL, email TEXT UNIQUE NOT NULL, password TEXT NOT NULL, role TEXT NOT NULL DEFAULT 'Customer', branch TEXT );
CREATE TABLE IF NOT EXISTS menu_items ( id SERIAL PRIMARY KEY, name TEXT NOT NULL, category TEXT NOT NULL, price NUMERIC NOT NULL, is_special BOOLEAN DEFAULT FALSE, is_available BOOLEAN DEFAULT TRUE );
CREATE TABLE IF NOT EXISTS orders ( id SERIAL PRIMARY KEY, user_id INTEGER, branch TEXT NOT NULL, total NUMERIC NOT NULL, status TEXT NOT NULL DEFAULT 'Placed', created_at TIMESTAMP DEFAULT NOW() );
CREATE TABLE IF NOT EXISTS order_items ( id SERIAL PRIMARY KEY, order_id INTEGER REFERENCES orders(id) ON DELETE CASCADE, menu_item_id INTEGER REFERENCES menu_items(id), qty INTEGER NOT NULL, price NUMERIC NOT NULL );
CREATE TABLE IF NOT EXISTS reservations ( id SERIAL PRIMARY KEY, branch TEXT NOT NULL, name TEXT NOT NULL, email TEXT NOT NULL, party_size INTEGER NOT NULL, datetime TIMESTAMP NOT NULL, status TEXT NOT NULL DEFAULT 'Submitted', created_at TIMESTAMP DEFAULT NOW() );
CREATE TABLE IF NOT EXISTS suppliers ( id SERIAL PRIMARY KEY, name TEXT NOT NULL, category TEXT NOT NULL, phones TEXT, address TEXT );
CREATE TABLE IF NOT EXISTS employees ( id SERIAL PRIMARY KEY, role TEXT NOT NULL, name TEXT NOT NULL, branch TEXT, salary NUMERIC, schedule TEXT );
CREATE TABLE IF NOT EXISTS campaigns ( id SERIAL PRIMARY KEY, title TEXT NOT NULL, platform TEXT NOT NULL, budget NUMERIC NOT NULL, status TEXT, kpi TEXT, duration TEXT, audience TEXT, description TEXT );
CREATE TABLE IF NOT EXISTS expenses ( id SERIAL PRIMARY KEY, branch TEXT NOT NULL, month TEXT NOT NULL, category TEXT NOT NULL, amount NUMERIC NOT NULL, advisor_comment TEXT );
CREATE TABLE IF NOT EXISTS messages ( id SERIAL PRIMARY KEY, from_user_id INTEGER, to_role TEXT NOT NULL, body TEXT NOT NULL, created_at TIMESTAMP DEFAULT NOW() );
